### ISSUE TITLE
Solaire-mode Support?

### ISSUE THREAD

**Issue by ghost** [motform/stimmung-themes#5]
I like having Solaire-mode's slightly different background color for non-"real" buffers. I like gray8 for the `solaire-default-face` background color with this theme. 

![image](https://user-images.githubusercontent.com/31514792/160222872-a4761ab8-f9f9-4e74-b3b5-6a67c9b7aa5e.png)

A lot of faces use background colors though, and the darker solaire-mode face makes them a little less harmonious so I'd understand if you don't want to make solaire-mode part of the official theme. I didn't like how marginalia's annotations looked with solaire-mode on, so I'm doing `:hook (minibuffer-setup-hook . (turn-off-solaire-mode))` in a use-package form.

**Comment by motform** [comment]
Hi @dm19, great suggestion! I've wanted to try out `solaire-mode` for quite a while, but never really took the time to figure it out since it plays badly with extra margins and `window-divider-mode`. Anyway, here is what I came up with:

![SCR-20220326-evl](https://user-images.githubusercontent.com/30436214/160234065-a6d74dea-5926-42d0-89e2-b4cba6eab392.png)

![SCR-20220326-evs](https://user-images.githubusercontent.com/30436214/160234066-a2624a9d-3075-46c6-a8da-f60c130bf259.png) 

(ignore the broken macOS title bar)

I took your suggestion about `gray8` to heart and based the other faces around that that. I think the end result looks pretty nice, especially in the light version. What do you think?

In addition to adding the `solaire-mode` face, I've also revised the treemacs faces to be a lot calmer, removing all font backgrounds (does not really work) and underlines. This solves some of the problems you rightfully express and makes it a lot nicer to look at.

**Comment by ghost** [comment]
Looks great to me!

**Comment by motform** [comment]
Great, then I'll close this issue. Just shout if you (or anyone else) comes across a place where it looks off!
